development:
  adapter: mysql2
  encoding: utf8
  database: pin_clone_dev
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  database: pin_clone_test
  username: root
  password: root
